### ISSUE TITLE
Threads run in the context of pry/byebug hang in 2.0.0

### ISSUE THREAD

**Issue by travisp** [deivid-rodriguez/pry-byebug#51] opened 2015-01-30 03:19 UTC
On pry-byebug 1.3.3:

``
[1] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> x = Thread.new { sleep 0.1; print "x"; print "y"; print "z" }
=> #<Thread:0x007fbfbb0337c0@(pry):1 sleep>
[2] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> x.join 
xyz=> #<Thread:0x007fbfbb0337c0@(pry):1 dead>
``

On pry-byebug 2.0.0:
``
[1] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> x = Thread.new { sleep 0.1; print "x"; print "y"; print "z" }
=> #<Thread:0x007f807dd83600@(pry):1 sleep>
[2] pry(#<RSpec::Core::ExampleGroup::Nested_1>)> x.join 
``
^^ hangs indefinitely

We noticed this while trying to access a connection in capybara-webkit, where threads are used in the connection code: https://github.com/thoughtbot/capybara-webkit/issues/718

**Comment by travisp** [comment] 2015-01-30 03:45
More specifically, the above threads work on pry-byebug commit 5c72fb550c1e447b4fadcb110beff00ac28cdfbe, but not 2 commits later b0eba72a7727ef58a3eefa75878d8b164147bf5a (I can't test the commit in the middle because I get exceptions).

**Comment by deivid-rodriguez** [comment] 2015-02-18 20:55
Could you try to reproduce this using latest `pry-byebug` and `byebug` (from master). I think it should be fixed in `byebug`.

**Comment by travisp** [comment] 2015-02-22 16:18
@deivid-rodriguez Unfortunately it seems that in pry-byebug master 917c365dc7f36 and byebug master 99bd3269deb790 the problem still remains.

**Comment by deivid-rodriguez** [comment] 2015-02-27 18:25
You means the problem remains separately in `byebug`´s master or using `pry-byebug` (master) + `byebug` (master).

**Comment by olivierlacan** [comment] 2015-03-02 04:37
@deivid-rodriguez Running both `byebug` master and `pry-byebug` master I'm still seeing hangs inside of capybara-webkit threads as well. Is there anything that could help you with this issue?

Basic setup I have is rspec with Capybara and capybara-webkit.
In `spec_helper.rb`:
```ruby
Capybara.javascript_driver = :webkit

RSpec.configure do |config|
#...
  config.around(:each, js: true) do |example|
    Capybara.using_driver(:webkit, &example)
  end
end
```

In the spec itself:

```ruby
require 'spec_helper'

describe 'Something', js: true do
  it 'does something' do
    before do
      binding.pry
    end
  end
end
```

Running the spec, when the Pry session starts, any call to `find('#selector')` hangs indefinitely.

**Comment by deivid-rodriguez** [comment] 2015-03-02 12:55
Are you able to reproduce using byebug master _only_?

**Comment by olivierlacan** [comment] 2015-03-02 12:56
@deivid-rodriguez Yep. That's what I did originally. I had the last release of pry-byebug I think and byebug master.

**Comment by deivid-rodriguez** [comment] 2015-03-02 13:09
@olivierlacan Did you uninstall `pry-byebug`, installed `byebug`'s master branch and then reproduced this using `byebug` instead of `binding.pry`?

If that's the case, open an issue in `byebug`'s repo?

**Comment by travisp** [comment] 2015-03-07 16:16
@deivid-rodriguez I tested again with the latest (after 091cff) in byebug. With byebug alone the problem does not seem to exist. With pry-byebug the problem remains for me and https://github.com/thoughtbot/capybara-webkit/issues/718 seems to be an issue for me too.

**Comment by deivid-rodriguez** [comment] 2015-03-07 16:28
@travisp I guess this is because pry-byebug is not using latest byebug's master. This should be fixed in next release.

@olivierlacan Sorry if my last sentence sounded rude, it's missing "could you".. :)

**Comment by deivid-rodriguez** [comment] 2015-04-06 14:49
Closing for lack of feedback. Feel free to reopen if still happening.

**Closed by deivid-rodriguez** 2015-04-06 14:49 UTC

**Comment by travisp** [comment] 2015-05-26 14:13
@deivid-rodriguez on pry-byebug 3.1.0 and byebug 4.0, as well as pry-byebug ``master`` this still remains an issue -- any threads run in this context seem to hang.

**Comment by justin808** [comment] 2015-09-06 04:40
I just tried this and also ran into this issue. So still seems like an issue.

**Comment by deivid-rodriguez** [comment] 2015-09-06 10:37
This seems like a duplicate of #69. Let's comment there.
